### ISSUE TITLE
can I contribute an autotools build for this?

### ISSUE THREAD

**Issue by edhartnett** [NOAA-GFDL/GFDL_atmos_cubed_sphere#1]
@underwoo can I contribute an autotools build for this repo, as I did for FMS?

**Comment by underwoo** [comment]
Yes. We'll be happy to include an autotools build option.

**Comment by edhartnett** [comment]
https://www.youtube.com/watch?v=4An1BrG2u_4

**Comment by edhartnett** [comment]
Any existing build instructions? Is this built with the same build system as was used on FMS?

**Comment by edhartnett** [comment]
I am seeing this failure:

 ```
use atmos_co2_mod,      only: atmos_co2_rad, co2_radiation_override
    1
Fatal Error: Can't open module file ‘atmos_co2_mod.mod’ for reading at (1): No such file or directory
compilation terminated.

```

atmos_co2_mod.mod does not seem to be part of FMS. Where does it come from?

**Comment by wrongkindofdoctor** [comment]
@edhartnett Could you paste or attach the contents of the script(s) in your build workflow to aid with debugging?

**Comment by edhartnett** [comment]
I have put up a PR (#2) and it contains instructions for building.

The build uses a current copy of the FMS library, which I built from source and installed in /usr/local/fms (using the FMS autotools build system).

**Comment by edwardhartnett** [comment]
OK, I have a pretty good build system I think for the dev/gfdl branch, but we need to find all the missing dependencies. Once we locate each of those, I think we will be good to go for a build system for dev/gfdl.

Actually dev/gfdl is almost identical to master from a build point of view. Hopefully dev/emc is similar, so it will be easy to get a build system there too.

**Comment by bensonr** [comment]
With the current SHiELD build (not the same!!) and the CMake build system in use by the UFS, I am going to close this.  Feel free to reopen if you want to continue the discussion.
