### ISSUE TITLE
Total tracer mass is not conserved after adiabatic preconditioning

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-GFDL/GFDL_atmos_cubed_sphere#125]
**Describe the bug**
Adiabatic preconditioning of initial conditions (`na_init>0`) does not conserve the total mass of prognostic tracers.
This was discovered while performing experiments that involved cycling aerosol tracers using new atmospheric initial conditions at each cycle.

This issue is affecting P7-targeted prognostic aerosol experiments.

**To Reproduce**
Set `na_init` to a positive integer (usually `1`), then compute the total tracer mass before and after preconditioning and take the difference.

**Expected behavior**
I suggest rescaling mixing ratios of prognostic tracers every time `Atm%delp` is adjusted to account for the change in the layer's total mass.

**Comment by rmontuoro** [comment]
A different but related issue is being addressed with PR #93

**Comment by bensonr** [comment]
With no work towards this for 2.5 years, closing.   Feel free to reopen as needed.

**Comment by lharris4** [comment]
The adiabatic_init may not be as necessary when doing DA cycling since the
initialization shock is far smaller than when "cold-starting". It is true
that if dp is adjusted then the tracers should be appropriately adjusted to
conserve mass, but for many applications this may be of minor importance.
