### ISSUE TITLE
dev/emc branch does not build without CCPP as a pre-requisite.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-GFDL/GFDL_atmos_cubed_sphere#142]
**Describe the bug**
The removal (or replacement) of IPD with CCPP introduced an explicit dependency on CCPP of the dynamical core in the `dev/emc` branch. `#ifdef CCPP` was removed.
As a result, the dycore now needs to be provided a path to the compiled fortran modules from CCPP.
This change no longer allows the DA development in JEDI to use `dev/emc` branch for dry dynamical core testing.

The `#ifdef` protections to CCPP need to be reinstated to allow the use of the dynamical core without CCPP.

**Expected behavior**
Allow the dynamical core to be built without CCPP.

Tagging @climbfuji

**Comment by climbfuji** [comment]
Another option is to allow building a stub CCPP that has no physics, just the lightweight framework with an empty stub suite/scheme. I played with this when @aerorahul reported the issue to me first, and it worked just fine. This would also align better with the idea of having an abstract interface to the fast physics with different backends (GFDL physics, CCPP physics, no/stub physics) that the GFDL developers and I have been talking about in the recent months.

**Comment by lharris4** [comment]
This will need to be a priority. Many FV3-based models (especially GEOS,
F-GOALS, and much of the GFDL modeling hierarchy, including simplified
models in use for GFD research) do not use CCPP and there should be no
reason a dynamical core needs to be tied to any particular physics
framework. Dom has already made very good progress on this end.

Thanks,
Lucas

**Comment by climbfuji** [comment]
I created a PR to compile dev/emc without CCPP dependencies, only FMS and netCDF (because FMS needs it) are required:https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/231

That PR triggered a discussion, and @lharris4 suggested to use the new "intermediate physics" layer, available in the main branch, to accomplish the same. See https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/231#issuecomment-1441047312 and following comments.

**Comment by bensonr** [comment]
@climbfuji - With all of the current work in issue #231 and [here](https://github.com/JCSDA-internal/fv3-jedi-data/pull/65), I believe this can be closed.  If not, feel free to reopen

**Comment by climbfuji** [comment]
Ok with me, thanks!
