### ISSUE TITLE
dev/emc: bug in fv_regional_bc.F90 - need to check if cloud amount index is valid before resetting boundary conditions

### ISSUE THREAD

**Issue by DomHeinzeller** [NOAA-GFDL/GFDL_atmos_cubed_sphere#145]
See:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/86177e14cdf60ce53fc6ec15829a8876db0c7445/model/fv_regional_bc.F90#L3775

This assumes that all older input data sets with `nwat=6` have cloud amount as a prognostic tracer. This is not true, because some older input data sets were created with Thompson MP (which also has `nwat=6`). The line needs to be changed to
```
            if (cld_amt > 0) BC_side%q_BC(i,j,k,cld_amt) = 0.
```
or commented out if not needed (like in line 6817).

**Comment by lharris4** [comment]
That is correct; these sorts of checks should be used whenever necessary. Nobody should ever have to guess or assume the availability of a certain tracer!
