### ISSUE TITLE
Bug in driver/fvGFS/atmosphere.F90 causes compilation to fail

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-GFDL/GFDL_atmos_cubed_sphere#150]
**Describe the bug**
A bug in `driver/fvGFS/atmosphere.F90` causes compilation to fail when built without `-DINTERNAL_FILE_NML`. The code  that reads  the `atmos_model_nml` namelist is using an undeclared variable, `unit`, and is also using routines for opening and closing the namelist file (`open_namelist_file` and `close_file`) that are not made available with the appropriate `use` statements above.  

```
[ 89%] Building Fortran object FV3/CMakeFiles/fv3dycore.dir/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90.o
/opt/ufs-srweather-app/src/ufs-weather-model/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90(479): error #6404: This name does not have a type, and must have an explicit type.   [UNIT]
   unit = open_namelist_file ( )
---^
/opt/ufs-srweather-app/src/ufs-weather-model/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90(479): error #6404: This name does not have a type, and must have an explicit type.   [OPEN_NAMELIST_FILE]
   unit = open_namelist_file ( )
----------^
Using 8-byte addressing
Using pure routines.
Using allocatable derived type array members.
Using cray pointers.
compilation aborted for /opt/ufs-srweather-app/src/ufs-weather-model/FV3/atmos_cubed_sphere/driver/fvGFS/atmosphere.F90 (code 1)
```

The offending section is [here](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/ab026b79497ee00530ff3eb6b59dd9b9346e8e7d/driver/fvGFS/atmosphere.F90#L478-L485)

**To Reproduce**
This issue was discovered when building the `rrfs_ci` branch of GSL's fork of `ufs-srweather-app` with the Intel OneAPI 2021 compiler.  After bringing the `atmos_cubed_sphere` external up to the most recent `dev/emc` (to get other bug fixes) this bug remains.  To reproduce, clone [GSL's fork](https://github.com/NOAA-GSL/ufs-srweather-app) and check out the `rrfs_ci` branch.  Then build with Intel compiler as per usual instructions in the [Getting Started Guide](https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started)

**Expected behavior**
The build should succeed.

**System Environment**
Describe the system environment, include:
- OS: Ubuntu 20.04
- Compiler(s): Intel OneAPI 2021
- MPI type: Intel MPI from OneAPI 2021
- netCDF Version: 4.7.4
- Configure options: 
```
module purge

module use /opt/hpc-stack/modulefiles/stack

module load hpc/1.2.0
module load hpc-intel/2021
module load hpc-impi/2021
module load jasper/2.0.25
module load zlib/1.2.11
module load png/1.6.35
module load hdf5/1.10.6
module load netcdf/4.7.4
module load pio/2.5.3
module load esmf/8_1_1
module load fms/2021.03
module load bacio/2.4.1
module load crtm/2.3.0
module load g2/3.4.5
module load g2tmpl/1.10.0
module load ip/3.3.3
module load nemsio/2.5.2
module load sp/2.3.3
module load w3emc/2.7.3
module load w3nco/2.4.1
module load upp/10.0.9

module load gfsio/1.4.1
module load sfcio/1.4.1
module load landsfcutil/2.4.1
module load nemsiogfs/2.5.3
module load wgrib2/2.0.8-blarn


export CMAKE_C_COMPILER=mpiicc
export CMAKE_CXX_COMPILER=mpiicpc
export CMAKE_Fortran_COMPILER=mpiifort
export CMAKE_Platform=linux.intel

mkdir build
cd build

cmake .. -DCMAKE_INSTALL_PREFIX=..
make -j4 >& build.out &

**Additional context**

Although the bug was found when using the Intel OneAPI compiler, other compilers/versions will likely not build this code, either.

**Comment by laurenchilutti** [comment]
Fixed via PR #149
