### ISSUE TITLE
Wrong calendar sometimes used in nudging.

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/GFDL_atmos_cubed_sphere#155]
**Describe the bug**
The `calendar` variable should be changed to `"calendar"` on this line:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/03e416417226b97ea8ad9a6c85c54e8b684575c2/GFDL_tools/read_climate_nudge_data.F90#L265

This is causing the calendar attribute to not be read in the file, possibly leading to the wrong calendar being used in the run.

**To Reproduce**
Try any nudging run where the calendar attribute on the time axis is not gregorian.

**Expected behavior**
The correct calendar type should be used.

**System Environment**
This will probably happen on all systems.

**Additional context**

**Comment by menzel-gfdl** [comment]
@bensor @laurenchilutti Do you agree? Should I make a pull request?

**Comment by laurenchilutti** [comment]
Fixed by PR #157
