### ISSUE TITLE
UFS global fv3 dycore only  decomposition test does not reproduce with certain decomposition

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-GFDL/GFDL_atmos_cubed_sphere#158]
**Describe the bug**
It is found that with certain decomposition, the global fv3 test does not reproduce the control in dycore only mode.

**To Reproduce**
1) check out ufs-weather-model on hera (or other platforms) by:
git clone --recursive https://github.com/ufs-community/ufs-weather-model
2) run control test:
cd ufs-weather-model/tests
./rt.sh -k -n "control"
3) go to the run directory $RUNDIR (shown in ufs-weather-model/tests/log_hera.intel/run_control.log)
cd $RUNDIR
cp -rf control control_dyn
cd control_dyn
in control_dyn, change namelist: 
dycore_only = .true.
then do: sbatch job_card
4) rerun the test with different layout
cd $RUNDIR
cp -rf control_dyn control_dyn_layout8x3
cd control_dyn_layout8x3
rm PET* atmf* logf* sfcf* GFS*
change layout in the input.nml: 
layout = 8,3 
then submit the job again: sbatch job_card
5) compare results history file or restart file. The results are different.

My source code is at:
run directory is at:
/scratch1/NCEPDEV/stmp2/Jun.Wang/FV3_RT/rt_188351
control_dyn (layout=8,3)
control_dyn_decomp (layout=3,8)
control_dyn_decomp1 (layout=4,6)

if using layout = 4,6, the results are reproducing.

**Expected behavior**

**System Environment**
Describe the system environment, include:
- OS: [e.g. RHEL 7.2]
- Compiler(s): Type and version [e.g. Intel 19.1]
- MPI type, and version (e.g. MPICH, Cray MPI, openMPI)
- netCDF Version: For both C and Fortran
- Configure options: Any additional flags, or macros passed to configure

On hera, intel compiler 18.0.5.274, impi: 2018.0.4, hdf5/1.10.6,  netcdf/4.7.4

**Additional context**
Add any other context about the problem.  If applicable, include where any files
that help describe, or reproduce the problem exist.

**Comment by bensonr** [comment]
@junwang-noaa - can you confirm whether you were running with REPRO options specified?  As you may recall, GFDL only guarantees absolute reproducibility using those compiler options.

**Comment by bensonr** [comment]
I'm closing this as I believe it has been explained.
