### ISSUE TITLE
"area" diagnostics is missing cell_methods in fv_diagnostics.F90 causing postprocessing issues

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/GFDL_atmos_cubed_sphere#165]
**Describe the bug**
The "area" diagnostics on [line 417 of fv_diagnostics.F90](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/master/tools/fv_diagnostics.F90#L417) is missing the cell_methods call below:
```
if (id_area > 0)  id_dx = register_static_field( trim(field), 'dx', (/id_xt,id_y/),  call diag_field_add_attribute (id_area, 'cell_methods', 'area: sum')
```

The call was there but was removed (probably by mistake) in commit b2236328efa9.

This is causing issues in postprocessing (frepp) tools at gfdl.

**To Reproduce**
The issues are reproduce only through frepp tools. 
User reports bad results for "area" when regridded from CS to latlon (e.g., ESM4_amip_D1_am4p2_proto7b (dora #1669).)

**Expected behavior**
static "area" diagnostics should have cell_methods attribute.

**Comment by laurenchilutti** [comment]
This fix has been merged in.
