### ISSUE TITLE
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/GFDL_atmos_cubed_sphere#178]
I am building in an ubuntu aarch64/arm64 environment, using gfortran-10 with openmpi, within a docker container, and cloning repo version "main". I tried adding the option '-fallow-argument-mismatch' but this did not seem to have an impact. Even if it did, the guidance seems to highly recommend correcting this in the source:

"-fallow-argument-mismatch
Some code contains calls to external procedures with mismatches between the calls and the procedure definition, or with mismatches between different calls. Such code is non-conforming, and will usually be flagged with an error. This options degrades the error to a warning, which can only be disabled by disabling all warnings via -w. Only a single occurrence per argument is flagged by this warning. -fallow-argument-mismatch is implied by -std=legacy.

**Using this option is strongly discouraged**. It is possible to provide standard-conforming code which allows different types of arguments by using an explicit interface and TYPE(*)."

https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/c885c3e7d05f960c3aaa5074246eb0c5aefb81dc/tools/fv_treat_da_inc.F90#L159

```
mpif90 -Duse_libMPI -Duse_netCDF -DHAVE_SCHED_GETAFFINITY -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Duse_LARGEFILE -DUSE_GFSL63 -DGFS_PHYS -DNO_CMIP_DIAG -DINTERNAL_FILE_NML -DOVERLOAD_R4 -DOVERLOAD_R8 -DMOIST_CAPPA -DUSE_COND -Duse_netCDF -DHAVE_SCHED_GETAFFINITY -Duse_LARGEFILE  -I/opt/netcdf/include -I/opt/netcdf/include -fallow-argument-mismatch -fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check -O3 -fopenmp -I/opt/fms/include -L/opt/fms/lib  -c	/atmos_cubed_sphere/model/tp_core.F90
/atmos_cubed_sphere/tools/fv_treat_da_inc.F90:159:48:

  159 |       call _GET_VAR1 (ncid, 'lon', im, lon )
      |                                                1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
/atmos_cubed_sphere/tools/fv_treat_da_inc.F90:160:48:

  160 |       call _GET_VAR1 (ncid, 'lat', jm, lat )
      |                                                1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
make: *** [Makefile_fv3:85: fv_treat_da_inc.o] Error 1
make: *** Waiting for unfinished jobs....

```

If I add the option '-fallow-argument-mismatch' to the FCFLAGS and FFLAGS environment variables, I also get:

```
/atmos_cubed_sphere/tools/fv_nudge.F90:2298:3:

 2298 | 123   continue
      |   1
......
 2350 |          if ( r_vor < 1250.E3 ) goto 123
      |                                        2
Warning: Legacy Extension: Label at (1) is not in the same block as the GOTO statement at (2)
/atmos_cubed_sphere/tools/fv_nudge.F90:1343:46:

 1343 |     call _GET_VAR1 (ncid, 'lon', im, lon )
      |                                              1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
/atmos_cubed_sphere/tools/fv_nudge.F90:1344:46:

 1344 |     call _GET_VAR1 (ncid, 'lat', jm, lat )
      |                                              1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
/atmos_cubed_sphere/tools/fv_nudge.F90:1357:56:

 1357 |     call _GET_VAR1 (ncid, 'hyai', km+1, ak0, found )
      |                                                        1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
/atmos_cubed_sphere/tools/fv_nudge.F90:1360:49:

 1360 |     call _GET_VAR1 (ncid, 'hybi', km+1, bk0 )
      |                                                 1
Error: Type mismatch in argument 'var1' at (1); passed REAL(8) to REAL(4)
make: *** [Makefile_fv3:71: fv_nudge.o] Error 1
```

If I remove the options "-DOVERLOAD_R4 -DOVERLOAD_R8" it builds. However, the SHiELD team used these options for a 32-bit build so I assume they are necessary. I haven't tested the resulting executable yet.

**Comment by lharris4** [comment]
Hi, Steve. I see that OVERLOAD_R4 is being called with fdefault-real-8,
which would create a conflict; GET_VAR1 would be defined as get_var1_real
(single precision) whereas real :: lon, lat would be defined as real*8.

I believe that if you wish to compile double-precision, you need to remove
the OVERLOAD_R4 directive.

Thanks,
Lucas

**Comment by StevePny** [comment]
Hi Lucas,
I was aiming for a 32-bit production build. I didn't notice the "-fdefault-double-8 -fdefault-real-8" which must have come from the mkmf template file. I'm using "linux-ubuntu-trusty-gnu.mk", though at the moment I've chosen this arbitrarily. Is there a mkmf template that you prefer for a 32-bit build on ubuntu, or should I just remove these options from the template file using sed?

**Comment by lharris4** [comment]
Hi, Steve. I would just remove these options from the template file.

Thanks,
Lucas

**Comment by laurenchilutti** [comment]
Hi @StevePny did Lucas's suggestiong of removing these options from the template file help you resolve this issue.  If so, I will close this?

**Comment by bensonr** [comment]
With no response since Jan 11th to this issue - closing
