### ISSUE TITLE
Adding NN evaluation for FV3

### ISSUE THREAD

**Issue by tse-chunchen** [NOAA-GFDL/GFDL_atmos_cubed_sphere#186]
**Is your feature request related to a problem? Please describe.**
To facilitate neural network (NN) based correction to the state variables, I would like to introduce subroutines that define and evaluate a typical feedforward NN and call it from the model (similar to https://github.com/AlexBelochitski-NOAA/fv3atm_full_physics_nn_emulator/).

**Describe the solution you'd like**
* Current plan is to implement it in a similar way as the IAU update since they are both adding an extra term to the RHS of the tendency equations.
* The architecture and the trained weights and biases will be read in from an ascii file. This design is to ensure maximal compatibility with different machine learning packages with minimal effort.
* There will mainly be two subroutines: “init_NN” (initializing the NN) and “eval_NN” (evaluation of the NN) with flexibility of number of layers, neurons, etc. Both will be placed in the “atmos_cubed_sphere/tools/” (the same as the “fv_iau_mod.F90”).
* The two will be called in the “atmos_model.F90”:
  * The “init_NN” will be called in subroutine: atmos_model_init
  * The “eval_NN” together with the preparation of the input data will be called after the physics update in subroutine: “update_atmos_radiation_physics”
  * The output will then update the state variables through the API “atmosphere_state_update” of “atmosphere.mod”

**Describe alternatives you've considered**
No.

**Additional context**
ufs-community/ufs-weather-model/issues/#1184
NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/#186
NOAA-EMC/fv3atm/issues/#522

@pjpegion @frolovsa @AlexBelochitski-NOAA

**Comment by lharris4** [comment]
Hi, Tse-Chun. Is there any possibility that you could follow the embedded
ML development being done by the Allen Institute?

https://github.com/ai2cm/fv3net

Thanks,
Lucas

**Comment by pjpegion** [comment]
I did a quick look at that github repo, and it looks like they wrote a python wrapper around the atmosphere model.  I do not see how that would would work in a fully coupled model where the atmosphere and ocean models are operating at different timesteps, and we would only be accessing certain processors.  It might work, but seems overly complicated. 
This proposed method keeps everything in the model as fortran, which is much simpler to interface with the rest of the model.

**Comment by lharris4** [comment]
Hi, Phil. I am increasingly concerned about the number of new diagnostics
that are being added to FV3. In particular if this is to emulate the
physics it should go in the physical parameterizations and not FV3, and it
should use its existing DA or physics update interfaces.

The python wrapper provides a simple plug-in interface that is easily
extensible without needing significant modifications to the base code. It
has nothing to do with differing timesteps. However if implementation of
the wrapper would be too much work then please use the existing FV3
interfaces to the physics and DA.

Thanks,
Lucas

**Comment by pjpegion** [comment]
This is not a physics emulator, but similar to IAU, which is a nudging technique.
 I thought this would go in the fv3GFS /driver/atmosphere.F90. Perhaps the driver should move out of the GFDL_atmos_cubed_sphere repo.

**Comment by tse-chunchen** [comment]
Hi Lucas,

To provide some context, we will be using this for correcting systematic
errors. It will be like an online state-dependent postprocessing. Hope this
helps. I should add the use case into the description.

Thanks
Tse-Chun

**Comment by lharris4** [comment]
Hi, Tse-Chun, Phil. I really don't think FV3 is the right place for this; it perhaps should sit at the atmos_model level instead.

Thanks,
Lucas

**Comment by lharris4** [comment]
Hi, Tse-Chun, Phil. I really don't think FV3 is the right place for this; it perhaps should sit at the atmos_model level instead and use existing APIs. I would need a good justification why the existing APIs are insufficient before adding new functionality to FV3 to support this.

Also if there is an interest in adding ML hooks to the UFS I would strongly suggest coordinating with the mature AI2 effort, which has been doing very productive work already and is funded through 2026.

Thanks,
Lucas

**Comment by bensonr** [comment]
@junwang-noaa @tse-chunchen - is this still something being actively pursued?  If not, please let us know.  Otherwise, this issue will be closed by the end of October

**Comment by frolovsa** [comment]
@bensonr we are just restarting work on this. @tse-chunchen left at the beginning of the year and things have slowed down after that.

**Comment by bensonr** [comment]
@frolovsa - thank you for the prompt response.  Will you be taking the suggestion of @lharris4 and implementing at a layer outside of the dynamical core proper?  If so, I would appreciate you closing out this ticket while you continue to use the one open in the ufs-weather-model/#1184 for tracking purposes.

**Comment by frolovsa** [comment]
@bensonr lets pick it up after the potential shut down.

**Comment by frolovsa** [comment]
we can close it now

**Comment by bensonr** [comment]
closing issue with the approval of @frolovsa
