### ISSUE TITLE
"Error: More actual than formal arguments in procedure call at (1)" in fv_diagnostics.F90

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/GFDL_atmos_cubed_sphere#189]
I am getting this error during compilation using:
```
make -j ${MAKEJOBS} OPENMP=Y AVX=${avx} NETCDF=3 ${COMP} 32BIT=Y NCEP_LIBS="${FMS_LIB}/libFMS.a ${GFS_LIB}/libgfs.a ${NCEP_LIBS}" -f Makefile_fv3
```

```
/atmos_cubed_sphere/tools/fv_diagnostics.F90:1355:126:

 1355 |     call fv_diag_column_init(Atm(n), yr_init, mo_init, dy_init, hr_init, do_diag_debug, do_diag_sonde, sound_freq, m_calendar)
      |                                                                                                                              1
Error: More actual than formal arguments in procedure call at (1)
make: *** [Makefile_fv3:51: fv_diagnostics.o] Error 1
```

From:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/998898ca1b70be3ff8f7a0a7505aa9bb3d3ec80e/tools/fv_diagnostics.F90#L1355

It looks like there are actually more arguments being passed than allowed:

From:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/c885c3e7d05f960c3aaa5074246eb0c5aefb81dc/GFDL_tools/fv_diag_column.F90#L53

Is this a bug? If so, is it safe to delete the m_calendar argument in fv_diagnostics.F90?

**Comment by lharris4** [comment]
Hi, Lauren. Thanks for taking care of this.

Lucas
