### ISSUE TITLE
Error in vmr adjustment in FV3

### ISSUE THREAD

**Issue by fabienpaulot** [NOAA-GFDL/GFDL_atmos_cubed_sphere#228]
**Describe the bug**
FV3 fv_update_phys and fv_dynamics require tracers to be in mmr units. 
There is no adjustment for vmr tracers in fv_dynamics and the correction used in fv_update_phys is wrong. 

**To Reproduce**
Turn off all sources and sink of any vmr tracers. The burden is not conserved. 

**Expected behavior**
VMR global burden should be conserved by FV3.

**System Environment**
NOAA HPC

**Comment by lharris4** [comment]
Hi, Fabien. Thank you for filing this issue.

Many of us from traditional weather/climate backgrounds tend to use different terminology than do atmospheric chemists. To clarify, am I correct when I say:

- "Global burden" means global mass of a species in the atmosphere;
- MMR (molar mass ratio) means specific ratio of a given species/substance, defined with respect to total mass (dry air + water vapor + condensates) as in FV3; and 
- VMR (volume mass ratio) means moles of substance per moles of total mass, calculated by q/Mw_air where Mw_air is the  molar weight of the moist air in a grid cell? (Side note: recall that a mole of any ideal gas always takes up the same volume given the same temperature and pressure.)

Thanks for your help. I would like to make sure everyone understands all the terms, to avoid confusion down the road.

**Comment by fabienpaulot** [comment]
Hi Lucas, this is all correct. 
Fabien

**Comment by lwhorowitz** [comment]
@lharris4, just a few minor clarifications:

MMR = mass mixing ratio, defined as you said as mass of substance per unit total mass (dry air + water vapor + condensates)

VMR = volume mixing ratio, defined as moles of substance per total moles (dry air + water vapor + condensates)

The relationship between the two is VMR_x = MMR_x * MW_air / MW_x, where MW_x is the molar mass of substance x, and MW_air is the molar mass of dry air + water vapor + condensates (which varies with changes in water tracer abundances).

**Comment by bensonr** [comment]
fixed in PR #232
