### ISSUE TITLE
Index '0' of dimension 1 of array 'des' below lower bound of 1

### ISSUE THREAD

**Issue by StevePny** [NOAA-GFDL/GFDL_atmos_cubed_sphere#234]
I am working on migrating our pre-202204 SHiELD code (old-main) to the new 202210 tag. I'm running SHiELD with a configuration as close as possible to the regional_nest_Laura test case with a few changes: (1) initial conditions are changed to 9/1/22 0Z at 1/2-degree (C192) resolution, (2) the 'nest' namelist option is removed, and (3) the lines in input.nml under namelist "gfdl_mp_nml" are commented out based on recommendations from Lucas and Linjiong. I'm also compiling in 'debug' mode via mk_make.

I'm getting this runtime error:
```
At line 7233 of file /SHiELD_SRC/GFDL_atmos_cubed_sphere/model/gfdl_mp.F90
Fortran runtime error: Index '0' of dimension 1 of array 'des' below lower bound of 1
```

For reference, gfdl_mp.F90 line 7233 and a few lines before:
```
    tmin = tice - 160.
    ap1 = 10. * dim (tk, tmin) + 1.
    ap1 = min (2621., ap1)
    qs_core = es_core (length, tk, table, des) / (rvgas * tk * den)
    it = ap1 - 0.5
    dqdt = 10. * (des (it) + (ap1 - it) * (des (it + 1) - des (it))) / (rvgas * tk * den)
```

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/d2e5bef344b64d6a10524479b3288717239fb2a2/model/gfdl_mp.F90#L7233

Are there any insights for this error?

**Comment by lharris4** [comment]
Hi, Steve. Sorry for the delay over the holidays.

This sort of out-of-range error within the microphysics usually means that
there is either an extreme value of the temperature (either far too cold or
too warm) or that numerical instability has created NaNs, which the lookup
table code shown here is unable to handle.

Lucas

**Comment by StevePny** [comment]
As an update, I believe this error was fixed by upgrading to the most recent version of FMS - in this case "2022.04"

**Comment by lharris4** [comment]
Hi, Steve. Glad to hear that. We have found a number of times that upgrades
to FMS have been able to solve some unusual problems.

Lucas
