### ISSUE TITLE
Total energy diagnostic units metadata is incorrect

### ISSUE THREAD

**Issue by mcgibbon** [NOAA-GFDL/GFDL_atmos_cubed_sphere#235]
**Describe the bug**
[compute_total_energy](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/model/fv_mapz.F90#L896) computes an output of units `J / m^2 * gravity`, but the [total energy diagnostic](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/tools/fv_diagnostics.F90#L1126) reports the units as `J/kg`.

**To Reproduce**
Inspect the code - this isn't a bug you can produce in an automated way without doing something like a full run and then trying to compute a closed energy budget (which is how I ended up here).

**Expected behaviour**
I'd expect the units of the diagnostic is supposed to be `J/m^2`, and that the diagnostic code itself has a bug and should be dividing by gravity.

**Comment by lharris4** [comment]
Hi, Jeremy. Thanks for pointing this out. Indeed the total energy diagnostic comes from fv_dynamics, and not from fv_diagnostics as we would expect:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/model/fv_dynamics.F90#L367

This routine does not divide by grav, which doesn't make much difference for the energy conservation calculation (the fixer divides by delp before applying the temperature increment) but will mean the diagnostic is off by a factor of g.

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/model/fv_mapz.F90#L799

The calculation in fv_diagnostics appears to not be used.

**Comment by bensonr** [comment]
@lharris4 - is this a 'wontfix' or ???

**Comment by lharris4** [comment]
We should fix this. Either @JosephMouallem or @kaiyuan-cheng would be best to address this.
