### ISSUE TITLE
add new parameter input_fv3gfs to specify data source for regional model LBC processing

### ISSUE THREAD

**Issue by Jili-Dong** [NOAA-GFDL/GFDL_atmos_cubed_sphere#252]
Currently FV3 will read data source from gfs_data.nc global attribute "source" to decide how LBC will be processed for regional model, e.g. RRFS. Sometimes there is no global attribute "source" in gfs_data.nc, particularly after regional cycled data assimilation, even though the data source is fv3gfs. This will cause FV3 to handle LBCs as they are from old GFS spectrum model.

A new parameter "input_fv3gfs" will be added in namelist to let users specify if the input source is fv3gfs or not. A .true. input_fv3gfs will override get_data_source subroutine. This parameter is set to .false. by default and not expected to affect existing RTs.

A PR will be submitted shortly.

**Comment by bensonr** [comment]
@Jili-Dong @junwang-noaa - I think this is a detrimental solution to this problem.  The correct solution is to ensure the dataset itself is correctly self-documented with appropriate global attributes.  This ensures the provenance of the dataset is known by any who attempt to use it.

**Comment by laurenchilutti** [comment]
Closing this Issue and the associated PR.  The recommended approach is described in the above comments.

**Comment by laurenchilutti** [comment]
Re-opening to continue discussion.  @Jili-Dong please feel free to continue a discussion in this issue and the associated PR.

**Comment by JacobCarley-NOAA** [comment]
This might be easier to explain in a small, quick tag-up among interested parties. Would folks be open to that?

**Comment by bensonr** [comment]
I'm open to it, but it'd have to be later in the week.

**Comment by Jili-Dong** [comment]
It is noted that LBC files in regional model (e.g. RRFS) contain the global attribute documenting the data source. We could modify get_data_source to read in LBC attribute and create another internal parameter to separate IC and LBC processing.

**Comment by Jili-Dong** [comment]
based on the discussions among GFDL, EMC and GSL, the related PR was modified to:

1. add a new subroutine to read source attribute for IC and LBC separately
2. exit FV3 when no source attribute is found to avoid mistakenly taking no source attribute as legacy spectrum GFS

the updated PR removes the addition of new namelist parameter and raises FATAL error when no source attribute is found as the reviewers suggested.
