### ISSUE TITLE
gfdl_cloud_microphysics.F90 can't be compiled without -DUSE_INTERNAL_NML

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/GFDL_atmos_cubed_sphere#254]
**Describe the bug**
This code block fails to compile if you try to compile without the -DUSE_INTERNAL_NML flag
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/2021.03/driver/SHiELD/gfdl_cloud_microphys.F90#L3369-L3382
Since this code can't be used, it should be deleted.

**To Reproduce**
Try to compile (AM5) without -DUSE_INTERNAL_NML

**Expected behavior**
The code should at least compile

**System Environment**
This was build on gaeac4 with the intel 2021 compiler (not classic or oneapi)

**Additional context**

**Comment by thomas-robinson** [comment]
@bensonr is this removed in newer versions?  I think the newer AM5 is going to be using more updated code, but it the physics needed to be updated to be compatible with FMS 2023.01

**Comment by laurenchilutti** [comment]
@thomas-robinson in tag 2022.04 the file was removed.
