### ISSUE TITLE
Ubar not initialized for some SW dynamics test cases

### ISSUE THREAD

**Issue by bensonr** [NOAA-GFDL/GFDL_atmos_cubed_sphere#255]
**Describe the bug**
For at least test_case = 0, 6, 7, 9, there are no initial values given for Ubar.  When running in debug mode, there is a crash in [_init_winds_](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/main/tools/test_cases.F90#L311-#L316) due to undefined Ubar.

**To Reproduce**
Run CI tests for BTwave, BLvortex, or RHwave after compiling solo SW executable.

**Expected behavior**
Expect Ubar to be defined within each select case option in _init_case_

**System Environment**
Describe the system environment, include:
all compilers that do not initialize all variables to zero by default

**Additional context**
N/A

**Comment by lharris4** [comment]
Hi, Rusty. For all of these cases `Ubar` should be 0. The variable `Ubar` is used as a temporary or for input to init_winds(), and is set on a case-by-case basis. (This file and especially `init_case()` have become a mess over the years and needs some restructuring to move case definitions into individual subroutines, to avoid some of this confusion.)

**Comment by bensonr** [comment]
Thanks @lharris4 I'll get the necessary definition(s) added and put in a PR
shortly.
