### ISSUE TITLE
Current 2020.02 tag does not compile with gnu 

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/GFDL_atmos_cubed_sphere#26]
I am trying to compile AM4 with gnu 7.3.0 in GAEA and I get the following error: 

```
/ncrc/home1/Uriel.Ramirez/awg/xanadu/cm4p12_xanadu/src/GFDL_atmos_cubed_sphere/tools/fv_diagnostics.F90:1991:74:

        if( idiag%id_slp>0 .or. idiag%id_tm>0 .or. idiag%id_any_hght>0 .or. idiag%id_hght3d .or. idiag%id_c15>0 .or. idiag%id_ctz ) then
                                                                          1
Error: Operands of logical operator '.or.' at (1) are LOGICAL(4)/INTEGER(4)
```

My build directory is in: 
/lustre/f2/dev/gfdl/Uriel.Ramirez/awg/xanadu/cm4p12_xanadu/ncrc4.gnu-prod/exec/

and my source directory is in: 
/ncrc/home1/Uriel.Ramirez/awg/xanadu/cm4p12_xanadu/src/GFDL_atmos_cubed_sphere

**Comment by uramirez8707** [comment]
@bensonr @laurenchilutti

**Comment by bensonr** [comment]
@uramirez8707 @laurenchilutti I will put in an update to fix this.
