### ISSUE TITLE
AM5OM4 coupled experiment fails in debug mode

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/GFDL_atmos_cubed_sphere#290]
**Describe the bug**
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/3b584df526ee68975a764789f96fab7056e4e122/driver/GFDL/atmosphere.F90#L209

The above lines fails in the debug mode with AM5_OM4 coupled model with the following coupler.res
```
    4        (Calendar: no_calendar=0, thirty_day_months=1, julian=2, gregorian=3, noleap=4)
     1     1     1     0     0     0        Model start time:   year, month, day, hour, minute, second
   101     1     1     0     0     0        Current model time: year, month, day, hour, minute, second
```

This is because the number of seconds is very large and it won't fit in an f9.1 format. We also shouldn't be hard coding 0 as the unit number. 

/lustre/f2/scratch/Uriel.Ramirez/am5/am5f3b1r1/c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg/ncrc5.intel23-classic-debug-openmp/stdout/run/c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg_1x0m2d_3456x4a_1002x1o1.o134581235
```
atmosphere_init: current_time_seconds = *********
forrtl: error (63): output conversion error, unit 0, file /proc/65909/fd/2
Image              PC                Routine            Line        Source            

Stack trace terminated abnormally.
```
**To Reproduce**
Run the c384L65_am5f3b1r1_OM4_p25_piControl_noBLING_DynVeg experiment in debug mode:
https://gitlab.gfdl.noaa.gov/m5/am5xml/-/blob/main/am5.xml?ref_type=heads#L188

**Expected behavior**
That should not fail

**System Environment**
Describe the system environment, include:
Intel23-classic on gaeac5 in debug mode

**Additional context**
N/A

**Comment by lharris4** [comment]
I believe this code was originally implemented to help debug the regional
domain capability in FV3. The write statement may no longer be necessary.
