### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-GFDL/GFDL_atmos_cubed_sphere#307]
**Is your question related to a problem? Please describe.**
Currently compiler warnings are suppressed when this repo (dev/emc branch) is compiled as a sub-module in the ufs-weather-model/fv3atm, which is not allowed by NCO (see https://github.com/ufs-community/ufs-weather-model/issues/1984). The following warnings must be fixed before this code is implemented in production:

```
FV3/atmos_cubed_sphere/tools/fv_nudge.F90(2488): warning #6371: A jump into a block from outside the block may have occurred.   [123]
FV3/atmos_cubed_sphere/model/fv_regional_bc.F90(4497): warning #6384: The INTEGER(KIND=4) value is out-of-range.   [9E9]
FV3/atmos_cubed_sphere/model/fv_regional_bc.F90(4547): warning #6384: The INTEGER(KIND=4) value is out-of-range.   [9E9]
FV3/atmos_cubed_sphere/model/fv_regional_bc.F90(4604): warning #6384: The INTEGER(KIND=4) value is out-of-range.   [9E9]
FV3/atmos_cubed_sphere/model/fv_regional_bc.F90(4663): warning #6384: The INTEGER(KIND=4) value is out-of-range.   [9E9]
FV3/atmos_cubed_sphere/model/fv_regional_bc.F90(4079): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [DELZ]
FV3/atmos_cubed_sphere/tools/test_cases.F90(5467): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [PK]
FV3/atmos_cubed_sphere/tools/test_cases.F90(5658): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [TP]
FV3/atmos_cubed_sphere/tools/test_cases.F90(5658): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [QP]
FV3/atmos_cubed_sphere/tools/module_diag_hailcast.F90(50): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [ISTATUS]
```

**Describe what you have tried**
A clear and concise description of what steps you have taken.  Include command
lines, and any messages from the command.

**Comment by amd-krishnoz** [comment]
@bensonr I was trying to compile the https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/ in a standalone manner and since `dev/emc` branch has support for cmake builds I am using that as of now. I assume the https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/ is useful to run bencmarks in standalone manner

**Comment by lharris4** [comment]
@amd-krishnoz Thank you for your interest in FV3. The FV3 code in this repository cannot be compiled by itself, and needs to be compiled within a driver as part of a full model ([SHiELD](https://github.com/NOAA-GFDL/SHiELD_build), UFS, GEOS, etc.). If you could describe what sort of benchmark you are interested in we can help you choose which path forward would be best for you.

We can take this offline if you need. My Email address is available at  [my website](https://www.gfdl.noaa.gov/lucas-harris-homepage/) (GitHub obscures Email addresses for privacy reasons).

**Comment by junwang-noaa** [comment]
@bensonr May I ask if you have any suggestions on resolving the warning messages? Thanks

**Comment by bensonr** [comment]
@junwang-noaa - I assumed Dusan was taking care of it since he created the issue.  If you'd like us to take care of it, we can.

**Comment by bensonr** [comment]
After discussions with @junwang-noaa, I have self-assigned and will be getting a PR out soon.
