### ISSUE TITLE
Downscaling sea surface current field from parent grid to nested grid

### ISSUE THREAD

**Issue by binli2337** [NOAA-GFDL/GFDL_atmos_cubed_sphere#312]
**Is your feature request related to a problem? Please describe.**
The surface ocean current will be included in the computation of air-sea fluxes in both parent grid and nested grid. The code needs to be updated to transfer the surface current filed from parent grid to the nested grid.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Related PR: #311

**Comment by bensonr** [comment]
#311 has been merged
