### ISSUE TITLE
Who uses the code in driver/fvGFS/atmosphere.F90

### ISSUE THREAD

**Issue by climbfuji** [NOAA-GFDL/GFDL_atmos_cubed_sphere#314]
**Is your question related to a problem? Please describe.**
I am looking at reorganizing the data storage model for the GFS data types in the UFS / FV3ATM. Doing that requires making changes in `driver/fvGFS/atmosphere.F90`. I am wondering who else than the UFS or other models that inherited the GFS data types (e.g. because of IPD first, then CCPP) uses this code. In other words, if I am making changes there, do I need to wrap all of them in `#ifdeg GFS_TYPES`?

If nobody outside the UFS-CCPP world uses this part of the code (somewhat suggested by the subdirectory `fvGFS`), then my life will be a lot easier and we can also simplify the code quite a bit (less `ifdef` = better).

**Describe what you have tried**
n/a

**Comment by wramstrom** [comment]
The HAFS moving nest code in the FV3/moving_nest directory uses the IPD structures, especially in moving_nest/fv_moving_nest_physics.F90.  I am happy to discuss further with you to coordinate any needed changes here.

**Comment by climbfuji** [comment]
Thanks for your quick feedback @bensonr and @wramstrom. So, if I understand you correctly, as long as I make sure that `driver/UFS/*` (I am going to rename that as part of the work) works for any of the UFS applications using the FV3 dynamical core, then we are ok; I do not need to worry about other modeling systems so long as I only touch the files in these directories.

**Comment by bensonr** [comment]
@climbfuji - yes, that is correct.

**Comment by bensonr** [comment]
PR #330 merged into dev/emc
