### ISSUE TITLE
IAU for soil temperature

### ISSUE THREAD

**Issue by tsga** [NOAA-GFDL/GFDL_atmos_cubed_sphere#319]
**Is your feature request related to a problem? Please describe.**
The atmospheric DA applies IAU increments on temperature (among other variables), while the land surface increments are applied once at the start of the DA (cycle?) window. This could lead to the land surface (soil and snow) temperature being out of sync with near surface atmospheric temperature.

**Describe the solution you'd like**
Update the existing IAU module to calculate IAU increments for soil temperature. Later on, this can be extended to include snow temperature, and if necssary, the other soil and snow variables.

**Describe alternatives you've considered**
A separate IAU module for land would be just a duplicate. Only few lines of code need to be added in the existing fv_iau_mod.F90

**Additional context**
Draft feature/branch with the proposed changes here: https://github.com/tsga/GFDL_atmos_cubed_sphere/tree/feature/sfciau

**Comment by tsga** [comment]
@CoryMartin-NOAA, @barlage, @ClaraDraper-NOAA
Please add (tag) anyone you think should be aware.

**Comment by bensonr** [comment]
The decision shouldn't be to minimize code, but whether you are creating a cross dependency on _components_.  With land acting as a peer component at the coupling level, does it make sense to have the dynamical core handle it's increment ingest.  Perhaps you should consult with higher level UFS development and design.
