### ISSUE TITLE
standalone run fv3 with test case

### ISSUE THREAD

**Issue by xyuan** [NOAA-GFDL/GFDL_atmos_cubed_sphere#321]
Is there anywhere to find some ideal test case for standalone FV3 test jobs? In this repo, there is no cmakefiles, and can't be built by the standalone mode.

**Is your question related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe what you have tried**
A clear and concise description of what steps you have taken.  Include command
lines, and any messages from the command.

**Comment by lharris4** [comment]
Hi, @xyuan . FV3 itself cannot be compiled directly but as part of a full model, with a driver. You can find the build system for SHiELD at [https://github.com/NOAA-GFDL/SHiELD_build](https://github.com/NOAA-GFDL/SHiELD_build) which includes an option for the standalone FV3 dycore, which we call solo_core.

Thanks,
Lucas

**Comment by xyuan** [comment]
Thanks very much, I will try to get the shield_build to try
