### ISSUE TITLE
Typo/bug in fv_grid_tools.F90 in dev/emc branch when print out grid corner indexes and locations

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-GFDL/GFDL_atmos_cubed_sphere#333]
**Describe the bug**
There is a typo/bug in [fv_grid_tools.F90](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/f060e857f184a4e8e988d8563794066525357336/tools/fv_grid_tools.F90#L2653C1-L2677C13) when print out the grid SW, NW, NE, SE CORNER indexes and lat/lon locations.
The source code lines of
ic = p_ind(1,1,1) ; jc = p_ind(1,1,1)
should be updated into:
ic = p_ind(1,1,1) ; jc = p_ind(1,1,2)
so that the jc gets the correct index. Otherwise, jc is always identical to ic, leading to wrong printout jc and lat/lon locations for the grid corners.

**Additional context**
This bug/typo was found/identified when checking UFS-HAFS moving-nesting forecast log. And you can see an proposed/example fix from this commit [4162fad](https://github.com/hafs-community/GFDL_atmos_cubed_sphere/commit/4162fad68d84db507bf25d4502673bc608c86600).

**Comment by lharris4** [comment]
Sorry for the delay @BinLiu-NOAA . I think you are correct. Could you go ahead and create an MR?

Thanks,
Lucas

**Comment by BinLiu-NOAA** [comment]
> Sorry for the delay @BinLiu-NOAA . I think you are correct. Could you go ahead and create an MR?
> 
> Thanks, Lucas

Thanks, @lharris4! PR #341 has been created accordingly to address this issue.

**Comment by bensonr** [comment]
merged into dev/emc branch with PR #341
