### ISSUE TITLE
Nests crashes in hydro mode

### ISSUE THREAD

**Issue by JosephMouallem** [NOAA-GFDL/GFDL_atmos_cubed_sphere#336]
**Describe the bug**
As in the title

**To Reproduce**
Run the nesting algorithm with the hydrostatic solver.

**Expected behavior**
Crash at the first timestep.

**Comment by bensonr** [comment]
@JosephMouallem - did we ever get a fix in for this?

**Comment by JosephMouallem** [comment]
Yes, it will be out in the new public release.

**Comment by bensonr** [comment]
Thanks Joseph.  Can we make sure to tie this issue to one of the PRs so it will autoclose?

**Comment by JosephMouallem** [comment]
Ok will do that, thanks.

**Comment by JosephMouallem** [comment]
Fixed in #364
