### ISSUE TITLE
FV3 is not able to apply DA increment when cold staring

### ISSUE THREAD

**Issue by pjpegion** [NOAA-GFDL/GFDL_atmos_cubed_sphere#339]
Currently,  the ability to read in an analysis increment is inside the warm_start section of the code.  So if a user tried to apply an increment to the initial condition, the model runs, but nothing is applied.  
 The solution is to move the call to read_da_inc outside the if external_ic/restart logic.

**Comment by bensonr** [comment]
PR #340 merged into dev/emc
