### ISSUE TITLE
Possible bug in fv_grid_tools.f90

### ISSUE THREAD

**Issue by ofuhrer** [NOAA-GFDL/GFDL_atmos_cubed_sphere#38]
The code [here](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/75b6ba3519dc91092ca8bcf409493a4182fa5712/tools/fv_grid_tools.F90#L620) on L620-621 in fv_grid_tools.f90 is...
`
if (ABS(grid_global(i,j,1,1)) < 1.d-10) grid_global(i,j,1,1) = 0.0
if (ABS(grid_global(i,j,2,1)) < 1.d-10) grid_global(i,j,2,1) = 0.0
`
...and should probably be...
`
if (ABS(grid_global(i,j,1,n)) < 1.d-10) grid_global(i,j,1,n) = 0.0
if (ABS(grid_global(i,j,2,n)) < 1.d-10) grid_global(i,j,2,n) = 0.0
`
...or taken out of the loop over regions.

**Comment by lharris4** [comment]
Hi, Oliver. Indeed the last index should be n.

Thanks,
Lucas

**Comment by bensonr** [comment]
@ofuhrer @lharris4 please make this fix and put in a PR for master.

**Comment by ofuhrer** [comment]
See [PR39](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/39/files).

**Comment by bensonr** [comment]
@ofuhrer I've assigned @lharris4 and @bensonr as reviewers
