### ISSUE TITLE
Read before write of sw_corner et al. in init_grid()?

### ISSUE THREAD

**Issue by ofuhrer** [NOAA-GFDL/GFDL_atmos_cubed_sphere#41]
The code in `fv_control_init()` in `fv_control.F90` loops over all grids and calls `init_grid()` on L590.
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/eee655598d58836a600c52a849e2ed69ab910653/model/fv_control.F90#L589-L596
Right after that grid_utils_init() is being called on L596. It turns out that that `sw_corner`, `se_corner`, `ne_corner` and `nw_corner` are only being set in the latter on L218.
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/eee655598d58836a600c52a849e2ed69ab910653/model/fv_grid_utils.F90#L218-L228
But these are being read by the former (see L888 and following to compute `area_c`).
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/eee655598d58836a600c52a849e2ed69ab910653/tools/fv_grid_tools.F90#L888-L897
This seems like a bug.

Note: Reported by @rheacangeo

**Comment by lharris4** [comment]
Hi, Oliver. This only affects the creation of area_c and rarea_c, and
apparently does not make more than minimal changes. You can move the
assignment of ??_corner to the routine which is called earlier to ensure
correctness of these two arrays at the corners.

Lucas

**Comment by lharris4** [comment]
Hi, Oliver. I would prefer it not to be moved into fv_arrays.F90 since this
routine is purely for allocating memory.

Lucas

**Comment by bensonr** [comment]
PR #113 cherry-picked into master branch
