### ISSUE TITLE
Need to create tag ufs-v1.1.0

### ISSUE THREAD

**Issue by climbfuji** [NOAA-GFDL/GFDL_atmos_cubed_sphere#52]
We need to tag the release/public-v1 branch as `ufs-v1.1.0` (hash 9808dcc). This version was tested successfully with the release/public-v1 branch of the ufs-weather-model, see https://github.com/ufs-community/ufs-weather-model/pull/198.

**Comment by bensonr** [comment]
ufs-v1.1.0 tag (9808dcc) created on Sept 4th as requested.

**Comment by climbfuji** [comment]
Thanks, @bensonr !
