### ISSUE TITLE
Rationalization of GFDL and EMC branches

### ISSUE THREAD

**Issue by lharris4** [NOAA-GFDL/GFDL_atmos_cubed_sphere#56]
At GFDL we are preparing a new public release of FV3 now that the [SHiELD paper](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020MS002223) has been published describing the in-line microphysics and positive-definite advection scheme within FV3. This release will also include a variety of new minor features and bugfixes implemented this year. 

I would like to get a better handle on what new features, functionality, fixes, etc. have been added to dev/emc since the 2018 FV3 delivery so that we can figure out what we might want to incorporate into the main (GFDL) branch and decide upon priorities for further FV3 development, and to work on re-factoring some older parts of the core. 

I am aware of the following:
- Significant LAM development, some of which has already been merged into the main.
- Variable-composition atmospheres
- Stochastic physics hooks
- AOML moving nest development (forthcoming)

Is there anything else I should know about?

Thanks,
Lucas

**Comment by bensonr** [comment]
The [public release](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/releases/tag/FV3-202101-public) was completed in January 2021.  This functionality was merged into dev/emc in March 2021 via PR #75.

There is now proper synchronization between all development branches in this project.
