### ISSUE TITLE
Missing module fv_nwp_nudge_mod in dev/gfdl branch

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/GFDL_atmos_cubed_sphere#6]
In the dev/gfdl branch, in file tools/external_ic.F90, we have:

`   use fv_nwp_nudge_mod,  only: T_is_Tv
`

I cannot find fv_nwp_nudge_mod anywhere. Where is it?

**Comment by bensonr** [comment]
tp_core.F90 is in the model/ directory.
