### ISSUE TITLE
Problem with remapping?

### ISSUE THREAD

**Issue by ofuhrer** [NOAA-GFDL/GFDL_atmos_cubed_sphere#70]
This issue has been reported by @rheacangeo.

The remapping of v-component of the velocity in `fv_mapz.F90` might contain an error. At the call of `map1_ppm()` the index range `is:ie+1` is passed, see...
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L552-L554 

Internally the arguments `pe0`, `pe3` and `gz` are dimensioned with this index range, see...
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L1386-L1404

While this is ok for `pe0` and `pe3`, this is obviously not the correct dimensioning for the `gz` variable, see https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/9078be0dfa50c94b65f5e2acff2d324ffe47aab4/model/fv_mapz.F90#L157

**Comment by lharris4** [comment]
Hi, Oli, Rhea. Thanks for pointing this out. This does appear to be a bug. Although gz (qs) is not used unless iv==-2, this could cause some serious memory problems. 

fv_mapz has gotten to be quite a mess. I did take some time last summer to clean it up a lot but haven't had an opportunity to test the cleaned-up code. 

Thanks,
Lucas

**Comment by bensonr** [comment]
@lharris4 - did we confirm and or fix this error?

**Comment by lharris4** [comment]
Unfortunately I have overlooked this problem. I looked at the code it appears that Rhea is right and this is indeed incorrect since for the `v` remapping `gz` should have dimensions `(is:ie+1)`. @JosephMouallem could you take a look and come up with a fix? Thanks.
