### ISSUE TITLE
model/dyn_core.F90 requires missing modules sw_core_mod and nh_core_mod.mod

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-GFDL/GFDL_atmos_cubed_sphere#8]
In model/dyn_core.F90 we have:
`  use sw_core_mod,        only: c_sw, d_sw
`

But sw_core_mod is missing.

Also:
`  use nh_core_mod,        only: Riem_Solver3, Riem_Solver_C, update_dz_c, update_dz_d, nest_halo_nh
`

But nh_core_mod is missing.

**Comment by bensonr** [comment]
sw_core_mod comes from model/sw_core.F90.

nh_core_mod comes from model/nh_core.F90 (in master) or from model_nh_null/nh_core.F90 (in dev/gfdl).
