### ISSUE TITLE
Bring documentation from UFS release branch to dev/emc

### ISSUE THREAD

**Issue by llpcarson** [NOAA-GFDL/GFDL_atmos_cubed_sphere#81]
Documentation updates made for the UFS v2 release need to be merged into master. @laurenchilutti is there anything UFS-specific that should *not* go into master?

**Comment by bensonr** [comment]
@llpcarson - I think the appropriate place is dev/emc.  I'm going to edit the issue to reflect that if you agree.

**Comment by llpcarson** [comment]
OK with me, thanks for the correction!

**Comment by laurenchilutti** [comment]
Yes, I agree with Rusty's correction.

**Comment by bensonr** [comment]
Closing - PR #94 was merged.
