### ISSUE TITLE
Regional IC/LBC routines allow only 'nemsio' as global attribute 'source'

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-GFDL/GFDL_atmos_cubed_sphere#95]
- The regional IC/LBC routines treat 'netcdf' and 'grib2' as the global attribute 'source' in input files differently from 'nemsio' though these three have the same logic in atmos_cubed_sphere.
- The global attribute 'source' is the output attribute of 'chgres_cube' and it has seven types. the other two names for 'netcdf' and 'grib2' need to be added to the regional IC/LBC routines in atmos_cubed_sphere.

**Comment by bensonr** [comment]
See the note in PR #96 as to why it was closed without being merged.

**Comment by bensonr** [comment]
Closing for now.  Feel free to re-open or create a new issue as the discussed solution comes into clearer focus.
